In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Load the dataset

In [2]:
data=pd.read_csv('ToyotaCorolla.csv')
data

,Id,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,...,Central_Lock,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Tow_Bar
0,1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,10,2002,46986,Diesel,90,1,...,1,1,1,0,0,0,1,0,0,0
1,2,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13750,23,10,2002,72937,Diesel,90,1,...,1,0,1,0,0,0,1,0,0,0
2,3,?TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13950,24,9,2002,41711,Diesel,90,1,...,0,0,1,0,0,0,1,0,0,0
3,4,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,14950,26,7,2002,48000,Diesel,90,0,...,0,0,1,0,0,0,1,0,0,0
4,5,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,13750,30,3,2002,38500,Diesel,90,0,...,1,1,1,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,1438,TOYOTA Corolla 1.3 16V HATCHB G6 2/3-Doors,7500,69,12,1998,20544,Petrol,86,1,...,1,1,1,0,1,1,1,0,0,0
1432,1439,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,10845,72,9,1998,19000,Petrol,86,0,...,0,0,1,0,0,1,1,0,0,0
1433,1440,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,8500,71,10,1998,17016,Petrol,86,0,...,0,0,1,0,0,0,1,0,0,0
1434,1441,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,7250,70,11,1998,16916,Petrol,86,1,...,0,0,0,0,0,0,1,0,0,0
1435,1442,TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors,6950,76,5,1998,1,Petrol,110,0,...,0,0,1,0,0,0,0,0,0,0

# Select the features you want to normalize

In [3]:
features = ['Price', 'Age_08_04', 'KM', 'HP', 'cc', 'Doors', 'Weight']

# Extract the selected features

In [4]:
X = data[features]

# 1. Min-Max Scaling

In [5]:
min_max_scaler = MinMaxScaler()
min_max_scaled = min_max_scaler.fit_transform(X)

# 2. Z-score Scaling

In [6]:
z_score_scaler = StandardScaler()
z_score_scaled = z_score_scaler.fit_transform(X)

# 3. Decimal Scaling

In [7]:
decimal_scaled = X.apply(lambda x: x / 10**(len(str(int(x.max()))) - 1))

# Convert the scaled data back to DataFrames for readability

In [8]:
min_max_scaled_df = pd.DataFrame(min_max_scaled, columns=features)
z_score_scaled_df = pd.DataFrame(z_score_scaled, columns=features)
decimal_scaled_df = decimal_scaled

# Print the first few rows of each scaled dataset

In [9]:
print("Min-Max Scaled Data:")
print(min_max_scaled_df.head())

Min-Max Scaled Data:
      Price  Age_08_04        KM        HP        cc     Doors    Weight
0  0.325044   0.278481  0.193355  0.170732  0.047619  0.333333  0.268293
1  0.333925   0.278481  0.300149  0.170732  0.047619  0.333333  0.268293
2  0.341030   0.291139  0.171647  0.170732  0.047619  0.333333  0.268293
3  0.376554   0.316456  0.197528  0.170732  0.047619  0.333333  0.268293
4  0.333925   0.367089  0.158433  0.170732  0.047619  0.333333  0.276423

In [10]:
print("\nZ-score Scaled Data:")
print(z_score_scaled_df.head())

Z-score Scaled Data:
      Price  Age_08_04        KM        HP        cc     Doors    Weight
0  0.763763  -1.771966 -0.574695 -0.768042  0.997419 -1.085139  1.758561
1  0.832715  -1.771966  0.117454 -0.768042  0.997419 -1.085139  1.758561
2  0.887877  -1.718184 -0.715386 -0.768042  0.997419 -1.085139  1.758561
3  1.163685  -1.610620 -0.547650 -0.768042  0.997419 -1.085139  1.758561
4  0.832715  -1.395491 -0.801028 -0.768042  0.997419 -1.085139  1.853577

In [11]:
print("\nDecimal Scaled Data:")
print(decimal_scaled_df.head())

Decimal Scaled Data:
   Price  Age_08_04       KM   HP   cc  Doors  Weight
0  1.350        2.3  0.46986  0.9  0.2    3.0   1.165
1  1.375        2.3  0.72937  0.9  0.2    3.0   1.165
2  1.395        2.4  0.41711  0.9  0.2    3.0   1.165
3  1.495        2.6  0.48000  0.9  0.2    3.0   1.165
4  1.375        3.0  0.38500  0.9  0.2    3.0   1.170